#ifndef DIPLAY_LWIPOPTS_H
#define DIPLAY_LWIPOPTS_H
#define NO_SYS 0
#define LWIP_IPV4 0
#define LWIP_IPV6 1
#define LWIP_IPV6_NUM_ADDRESSES 2
#define LWIP_IPV6_AUTOCONFIG 0
#define LWIP_IPV6_DUP_DETECT_ATTEMPTS 0
#define LWIP_IPV6_MLD 0
#define LWIP_ICMP6 1
#define IPV6_FRAG_COPYHEADER 1
#define LWIP_TCP 1
#define LWIP_UDP 1
#define LWIP_ETHERNET 1
#define LWIP_ARP 0
#define LWIP_DNS 0
#define LWIP_NETCONN 1
#define LWIP_SOCKET 1
#define LWIP_COMPAT_SOCKETS 0
#define LWIP_SOCKET_SELECT 1
#define LWIP_SOCKET_POLL 0
#define LWIP_NETCONN_FULLDUPLEX 1
#define LWIP_NETCONN_SEM_PER_THREAD 1
#define LWIP_SO_RCVTIMEO 1
#define LWIP_SO_SNDTIMEO 1
#define LWIP_SO_LINGER 1
#define LWIP_TCP_KEEPALIVE 1
#define SO_REUSE 1
#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1
#define MEM_ALIGNMENT 8
#define TCP_MSS 1440
#define TCP_WND (256 * 1024 - 4)
#define TCP_SND_BUF (128 * 1024)
#define TCP_SND_QUEUELEN 512
#define TCP_SNDLOWAT (16 * 1024)
#define LWIP_WND_SCALE 1
#define TCP_RCV_SCALE 2
#define TCP_QUEUE_OOSEQ 1
#define TCP_OOSEQ_MAX_BYTES (128 * 1024)
#define TCP_OOSEQ_MAX_PBUFS 128
#define DEFAULT_TCP_RECVMBOX_SIZE 128
#define DEFAULT_UDP_RECVMBOX_SIZE 128
#define DEFAULT_ACCEPTMBOX_SIZE 8
#define TCPIP_MBOX_SIZE 256
#define PBUF_POOL_SIZE 512
#define PBUF_POOL_BUFSIZE 1600
#define LWIP_STATS 0
#define SYS_LIGHTWEIGHT_PROT 1
#define LWIP_SOCKET_EXTERNAL_HEADERS 0
#endif
